version: "3"
services:
  node:
    build: web
    volumes:
      - ./web:/usr/src/app
    container_name: node-app
    command: sh -c "npm cache clean --force && yarn install && yarn start"
    ports:
      - "3000:3000"
    restart: always
    tty: true
  go:
    build: server
    volumes:
      - ./server:/usr/src/app
    container_name: go-app
    tty: true
    restart: always
volumes:
  node-data:
